// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP-VAM0sK6n5FEn4U_vgeS-iANmqk3Hbc',
    appId: '1:398359138001:web:2f155da3411ca18ee53ff0',
    messagingSenderId: '398359138001',
    projectId: 'cooking-e9fc3',
    authDomain: 'cooking-e9fc3.firebaseapp.com',
    storageBucket: 'cooking-e9fc3.firebasestorage.app',
    measurementId: 'G-Q6R5EJXNED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMjEaNxmtPekZkzNJ0DOXPkBj5rjNyfA4',
    appId: '1:398359138001:android:a5dc2179d815dc2ae53ff0',
    messagingSenderId: '398359138001',
    projectId: 'cooking-e9fc3',
    storageBucket: 'cooking-e9fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvAo1xan4MlgwzxR0AbOsT1-8q96n4FE',
    appId: '1:398359138001:ios:b2d0d769f1a3cfb3e53ff0',
    messagingSenderId: '398359138001',
    projectId: 'cooking-e9fc3',
    storageBucket: 'cooking-e9fc3.firebasestorage.app',
    iosBundleId: 'com.example.cookingHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvAo1xan4MlgwzxR0AbOsT1-8q96n4FE',
    appId: '1:398359138001:ios:b2d0d769f1a3cfb3e53ff0',
    messagingSenderId: '398359138001',
    projectId: 'cooking-e9fc3',
    storageBucket: 'cooking-e9fc3.firebasestorage.app',
    iosBundleId: 'com.example.cookingHealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP-VAM0sK6n5FEn4U_vgeS-iANmqk3Hbc',
    appId: '1:398359138001:web:07a2715593129745e53ff0',
    messagingSenderId: '398359138001',
    projectId: 'cooking-e9fc3',
    authDomain: 'cooking-e9fc3.firebaseapp.com',
    storageBucket: 'cooking-e9fc3.firebasestorage.app',
    measurementId: 'G-T9SQJQM8GT',
  );
}
